# ============================================================
# TontiFlow - Authentication Service
# Configuration centralisée du microservice d'authentification
# ============================================================

# ------------------------------------------------------------
# Identité du microservice
# ------------------------------------------------------------
spring.application.name=authentication-service

# Port HTTP utilisé par Authentication Service
server.port=8081


# ------------------------------------------------------------
# Eureka Service Discovery
# Permet au microservice de s'enregistrer auprès de Eureka
# ------------------------------------------------------------
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enregistrement du service dans Eureka
eureka.client.register-with-eureka=true

# Récupération de la liste des services disponibles
eureka.client.fetch-registry=true


# ------------------------------------------------------------
# PostgreSQL
# Base dédiée au microservice d'authentification
# PostgreSQL est exécuté dans Docker
# ------------------------------------------------------------
spring.datasource.url=jdbc:postgresql://localhost:5432/tontiflow_authentication

# Utilisateur PostgreSQL défini dans Docker
spring.datasource.username=postgres

# Mot de passe PostgreSQL défini dans Docker
spring.datasource.password=root

# Driver JDBC PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver


# ------------------------------------------------------------
# JPA / Hibernate
# ------------------------------------------------------------

# Gestion du schéma de la base de données
spring.jpa.hibernate.ddl-auto=none

# Affichage des requêtes SQL désactivé
spring.jpa.show-sql=false

# Formatage des requêtes SQL dans les logs
spring.jpa.properties.hibernate.format_sql=true


# ------------------------------------------------------------
# Flyway
# Les migrations versionnées gèrent la structure de la base
# ------------------------------------------------------------
spring.flyway.enabled=true