# ============================================================
# TontiFlow - User Service
# Configuration centralisée du microservice utilisateur
# ============================================================

# ------------------------------------------------------------
# Identité du microservice
# ------------------------------------------------------------

spring.application.name=user-service

# Port HTTP du User Service
server.port=8082


# ------------------------------------------------------------
# Eureka Service Discovery
# ------------------------------------------------------------

# Adresse du serveur Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

# Enregistrement du User Service auprès de Eureka
eureka.client.register-with-eureka=true

# Récupération de la liste des microservices
eureka.client.fetch-registry=true


# ------------------------------------------------------------
# PostgreSQL Docker
# ------------------------------------------------------------

# Base PostgreSQL dédiée au User Service
spring.datasource.url=jdbc:postgresql://localhost:5432/tontiflow_user

# Utilisateur PostgreSQL défini dans Docker
spring.datasource.username=postgres

# Mot de passe PostgreSQL défini dans Docker
spring.datasource.password=root

# Driver JDBC PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver


# ------------------------------------------------------------
# JPA / Hibernate
# ------------------------------------------------------------

# Le schéma est géré par Flyway
spring.jpa.hibernate.ddl-auto=validate

# Désactive l'affichage des requêtes SQL
spring.jpa.show-sql=false

# Formate les requêtes SQL dans les logs
spring.jpa.properties.hibernate.format_sql=true


# ------------------------------------------------------------
# Flyway
# ------------------------------------------------------------

# Active les migrations Flyway
spring.flyway.enabled=true